USE [master]
GO
/****** Object:  Database [LUGYMDS2]    Script Date: 5/10/2024 18:50:57 ******/
CREATE DATABASE [LUGYMDS2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LUGYMDS2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\LUGYMDS2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LUGYMDS2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\LUGYMDS2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [LUGYMDS2] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LUGYMDS2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [LUGYMDS2] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [LUGYMDS2] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [LUGYMDS2] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [LUGYMDS2] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [LUGYMDS2] SET ARITHABORT OFF 
GO
ALTER DATABASE [LUGYMDS2] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [LUGYMDS2] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [LUGYMDS2] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [LUGYMDS2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [LUGYMDS2] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [LUGYMDS2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [LUGYMDS2] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [LUGYMDS2] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [LUGYMDS2] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [LUGYMDS2] SET  ENABLE_BROKER 
GO
ALTER DATABASE [LUGYMDS2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [LUGYMDS2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [LUGYMDS2] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [LUGYMDS2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [LUGYMDS2] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [LUGYMDS2] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [LUGYMDS2] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [LUGYMDS2] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [LUGYMDS2] SET  MULTI_USER 
GO
ALTER DATABASE [LUGYMDS2] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [LUGYMDS2] SET DB_CHAINING OFF 
GO
ALTER DATABASE [LUGYMDS2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [LUGYMDS2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [LUGYMDS2] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [LUGYMDS2] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [LUGYMDS2] SET QUERY_STORE = OFF
GO
USE [LUGYMDS2]
GO
/****** Object:  Table [dbo].[CARRITO]    Script Date: 5/10/2024 18:50:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CARRITO](
	[CARRITOID] [int] IDENTITY(1,1) NOT NULL,
	[CLIENTE_ID] [int] NOT NULL,
	[MONTO_TOTAL] [float] NULL,
	[ESTADO] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CARRITOID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CARRITO_PRODUCTO]    Script Date: 5/10/2024 18:50:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CARRITO_PRODUCTO](
	[CARRITOID] [int] NOT NULL,
	[PRODUCTOID] [int] NOT NULL,
	[CANTIDAD] [int] NOT NULL,
	[PRECIO_UNITARIO] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[CARRITOID] ASC,
	[PRODUCTOID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[CLIENTE]    Script Date: 5/10/2024 18:50:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CLIENTE](
	[CLIENTEID] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[APELLIDO] [varchar](50) NOT NULL,
	[CUIT] [float] NOT NULL,
	[EMAIL] [varchar](50) NOT NULL,
	[TELEFONO] [float] NULL,
	[DIRECCION] [varchar](50) NULL,
 CONSTRAINT [PK__CLIENTE__71ABD0A798F3FAC0] PRIMARY KEY CLUSTERED 
(
	[CLIENTEID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FACTURA]    Script Date: 5/10/2024 18:50:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FACTURA](
	[NROFACTURA] [int] IDENTITY(1,1) NOT NULL,
	[CLIENTEID] [int] NOT NULL,
	[CARRITOID] [int] NOT NULL,
	[MONTO_TOTAL] [float] NOT NULL,
	[ESTADO] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[NROFACTURA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRODUCTO]    Script Date: 5/10/2024 18:50:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCTO](
	[PRODUCTOID] [int] IDENTITY(1,1) NOT NULL,
	[MODELO] [varchar](50) NOT NULL,
	[MARCA] [varchar](50) NOT NULL,
	[STOCK] [int] NOT NULL,
	[PRECIO] [float] NOT NULL,
	[CATEGORIA] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[PRODUCTOID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REMITO]    Script Date: 5/10/2024 18:50:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REMITO](
	[REMITOID] [int] IDENTITY(1,1) NOT NULL,
	[CARRITOID] [int] NOT NULL,
	[FECHAENTREGA] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[REMITOID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REMITO_PRODUCTO]    Script Date: 5/10/2024 18:50:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REMITO_PRODUCTO](
	[REMITOID] [int] NOT NULL,
	[PRODUCTOID] [int] NOT NULL,
	[NUMEROSERIE] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[REMITOID] ASC,
	[PRODUCTOID] ASC,
	[NUMEROSERIE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[CARRITO] ON 
GO
INSERT [dbo].[CARRITO] ([CARRITOID], [CLIENTE_ID], [MONTO_TOTAL], [ESTADO]) VALUES (1, 4, 0, 1)
GO
INSERT [dbo].[CARRITO] ([CARRITOID], [CLIENTE_ID], [MONTO_TOTAL], [ESTADO]) VALUES (2, 4, 0, 1)
GO
INSERT [dbo].[CARRITO] ([CARRITOID], [CLIENTE_ID], [MONTO_TOTAL], [ESTADO]) VALUES (3, 4, 0, 1)
GO
INSERT [dbo].[CARRITO] ([CARRITOID], [CLIENTE_ID], [MONTO_TOTAL], [ESTADO]) VALUES (4, 5, 0, 1)
GO
SET IDENTITY_INSERT [dbo].[CARRITO] OFF
GO
SET IDENTITY_INSERT [dbo].[CLIENTE] ON 
GO
INSERT [dbo].[CLIENTE] ([CLIENTEID], [NOMBRE], [APELLIDO], [CUIT], [EMAIL], [TELEFONO], [DIRECCION]) VALUES (4, N'Carlos', N'Rey', 20290774544, N'reycarlosf@msn.com', 1130873343, N'Arenales 1093')
GO
INSERT [dbo].[CLIENTE] ([CLIENTEID], [NOMBRE], [APELLIDO], [CUIT], [EMAIL], [TELEFONO], [DIRECCION]) VALUES (5, N'Yanina', N'Larrarte', 27112233444, N'yanina@rey.com', 1187654321, N'Arenales 1093')
GO
SET IDENTITY_INSERT [dbo].[CLIENTE] OFF
GO
SET IDENTITY_INSERT [dbo].[PRODUCTO] ON 
GO
INSERT [dbo].[PRODUCTO] ([PRODUCTOID], [MODELO], [MARCA], [STOCK], [PRECIO], [CATEGORIA]) VALUES (1, N'RTX3060', N'Asus', 10, 250, N'Placa de video')
GO
INSERT [dbo].[PRODUCTO] ([PRODUCTOID], [MODELO], [MARCA], [STOCK], [PRECIO], [CATEGORIA]) VALUES (3, N'RTX4090', N'GIGABYTE', 5, 750, N'Placa de Video')
GO
INSERT [dbo].[PRODUCTO] ([PRODUCTOID], [MODELO], [MARCA], [STOCK], [PRECIO], [CATEGORIA]) VALUES (4, N'RTX4070', N'ZOTAC', 5, 500, N'Placa de Video')
GO
INSERT [dbo].[PRODUCTO] ([PRODUCTOID], [MODELO], [MARCA], [STOCK], [PRECIO], [CATEGORIA]) VALUES (5, N'14400f', N'INTEL', 25, 250, N'Procesador')
GO
INSERT [dbo].[PRODUCTO] ([PRODUCTOID], [MODELO], [MARCA], [STOCK], [PRECIO], [CATEGORIA]) VALUES (6, N'14700K', N'INTEL', 0, 450, N'Procesador')
GO
INSERT [dbo].[PRODUCTO] ([PRODUCTOID], [MODELO], [MARCA], [STOCK], [PRECIO], [CATEGORIA]) VALUES (7, N'9700K', N'INTEL', 0, 200, N'Procesador')
GO
INSERT [dbo].[PRODUCTO] ([PRODUCTOID], [MODELO], [MARCA], [STOCK], [PRECIO], [CATEGORIA]) VALUES (8, N'9700', N'INTEL', 8, 180, N'Procesador')
GO
SET IDENTITY_INSERT [dbo].[PRODUCTO] OFF
GO
ALTER TABLE [dbo].[CARRITO]  WITH CHECK ADD  CONSTRAINT [FK__CARRITO__Cliente__286302EC] FOREIGN KEY([CLIENTE_ID])
REFERENCES [dbo].[CLIENTE] ([CLIENTEID])
GO
ALTER TABLE [dbo].[CARRITO] CHECK CONSTRAINT [FK__CARRITO__Cliente__286302EC]
GO
ALTER TABLE [dbo].[CARRITO_PRODUCTO]  WITH CHECK ADD FOREIGN KEY([CARRITOID])
REFERENCES [dbo].[CARRITO] ([CARRITOID])
GO
ALTER TABLE [dbo].[CARRITO_PRODUCTO]  WITH CHECK ADD FOREIGN KEY([PRODUCTOID])
REFERENCES [dbo].[PRODUCTO] ([PRODUCTOID])
GO
ALTER TABLE [dbo].[FACTURA]  WITH CHECK ADD FOREIGN KEY([CARRITOID])
REFERENCES [dbo].[CARRITO] ([CARRITOID])
GO
ALTER TABLE [dbo].[FACTURA]  WITH CHECK ADD  CONSTRAINT [FK__FACTURA__Cliente__2F10007B] FOREIGN KEY([CLIENTEID])
REFERENCES [dbo].[CLIENTE] ([CLIENTEID])
GO
ALTER TABLE [dbo].[FACTURA] CHECK CONSTRAINT [FK__FACTURA__Cliente__2F10007B]
GO
ALTER TABLE [dbo].[REMITO]  WITH CHECK ADD FOREIGN KEY([CARRITOID])
REFERENCES [dbo].[CARRITO] ([CARRITOID])
GO
ALTER TABLE [dbo].[REMITO_PRODUCTO]  WITH CHECK ADD FOREIGN KEY([PRODUCTOID])
REFERENCES [dbo].[PRODUCTO] ([PRODUCTOID])
GO
ALTER TABLE [dbo].[REMITO_PRODUCTO]  WITH CHECK ADD FOREIGN KEY([REMITOID])
REFERENCES [dbo].[REMITO] ([REMITOID])
GO
USE [master]
GO
ALTER DATABASE [LUGYMDS2] SET  READ_WRITE 
GO
